core:
  lang: en
  command-aliases: codex,codexengine,codexcore

locale:
  world-names:
    world: 'World'
    world_nether: 'Nether'
    world_the_end: 'The End'

Features:
  chat-enabled: true
  scoreboards-enabled: true

Settings:
  command-cooldown-message: "&4Please wait &6{time} seconds &4before using the command again."

file-timings: false

bungee: false
bungee_id: codexcore

# Commands executed for player on login. The following placeholders are supported:
# {player} - name of player
onJoin: []
onFirstJoin: []
# An example for onJoin could be
# onJoin:
#  - delay: 100
#    as: CONSOLE
#    cmd: give {player} cookie 1

# Commands executed when player click on block, use type of -1 to ignore type.
# Players with 'core.oninteract.bypass' permission will be ignored.
onInteract: []
# An example for onInteract could be
# onInteract:
#  - material: CRAFTING_TABLE
#    type: -1
#    cancelAction: true
#    delayedCommands:
#      - delay: 0
#        as: CONSOLE
#        cmd: give {player} cookie 1

debug: false
removeBoatOnExit: true

unstuck:
  cooldown: 30
  warmup: 5